import type { Metadata } from "next";
import { Open_Sans, Roboto } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Nav from '../components/nav/Nav';
import Footer from '../components/footer/Footer';
import AuthModal from '../components/auth/authModal';
import styleNav from '../components/nav/nav.module.css';
import { ReduxProvider } from './ReduxProvider';

const geistOpen_Sans = Open_Sans({
  variable: "--font-open-Sans",
  subsets: ["latin"],
});

const geistRoboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "OneFlix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="https://kit.fontawesome.com/0241eb844d.js" crossOrigin="anonymous" />
      </head>
      <body className={`${geistOpen_Sans.variable} ${geistRoboto.variable}`}>
        <ReduxProvider>
          <Nav />
          <main className={styleNav.mainContent}>
            {children}
          </main>
          <Footer />
          <AuthModal />
        </ReduxProvider>
      </body>
    </html>
  );
}